Alchemy.user_class_name     = 'User'          # Defaults to 'User'
Alchemy.current_user_method = 'current_user'     # Defaults to 'current_user'
Alchemy.signup_path         = '/users/sign_up'      # Defaults to '/signup'
Alchemy.login_path          = '/users/sign_in'       # Defaults to '/login'
Alchemy.logout_path         = '/users/sign_out'      # Defaults to '/logout'
Alchemy.logout_method       = 'delete'   # Defaults to 'delete'
